### ISSUE TITLE
SDF Texture valid size

### ISSUE THREAD

**Issue by vorg** [armory3d/sdfgen#1]
What's the size of the generated *.bin sdf texture?

SDF Render target is 50 x 2500
https://github.com/armory3d/sdfgen/blob/master/build/krom/Scene.arm#L9

but sdftex is 2500 x 50
https://github.com/armory3d/sdfgen/blob/master/viewer/Sources/Main.hx#L18

**Comment by luboslenco** [comment]
Fixed the viewer in https://github.com/armory3d/sdfgen/commit/2fe15ae4d4f0a4f0325a51bf5c73bd29a2c0e400, it's 50x2500. Thanks for notice!
