### ISSUE TITLE
Query how is this compared to christopherbatty/SDFGen?

### ISSUE THREAD

**Issue by ynotstartups** [armory3d/sdfgen#2]
I have been using the christopherbatty/SDFGen about a year ago, where the SDFs are used in our filter from the link below 

[https://www.myminifactory.com/object/3dfilters?frame=0&model=33936&target=sphere&filter=Morphing](url)

I am just queries how does your sdfgen compared to his?

**Comment by luboslenco** [comment]
Heyho,

`armory3d/sdfgen` is a gpu-based implementation, `christopherbatty/SDFGen` appears to be a cpu-based implementation. Generally `armory3d/sdfgen` aims to favor speed, so the results may be less precise.
