### ISSUE TITLE
Compute-based SDF

### ISSUE THREAD

**Issue by boberfly** [armory3d/sdfgen#3]
I came across a compute-based way of generating 3D SDFs in AMD's TressFX:
https://github.com/GPUOpen-Effects/TressFX/blob/master/amd_tressfx/src/Shaders/TressFXSDFCollision.hlsl

Not sure how usable this as it's meant for collision is but interesting none the less! Might be a faster approach...

**Comment by luboslenco** [comment]
Cool!
